version: '3'
services:
  php8.1:
    image: webdevops/php-dev:8.1
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=coverage
  php8.0:
    image: webdevops/php-dev:8.0
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=coverage
  php7.4:
    image: webdevops/php-dev:7.4
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=coverage
  php7.3:
    image: webdevops/php-dev:7.3
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=coverage
  php7.2:
    image: webdevops/php-dev:7.2
    volumes:
      - ./:/app/
    working_dir: /app
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=coverage

  db:
    image: postgres
    ports:
      - 7929:5432
    environment:
      POSTGRES_DB: testing
      POSTGRES_PASSWORD: secret